Add OpenShift 4.8 release notes
appuio/openshift4-docs pull request #108
Opened 2021-08-16 14:04 UTC by tobru

2021-08-16 15:17 UTC, simu requested changes
Looks like the file `references/release_notes.adoc` is missing

2021-08-16 15:20 UTC, tobru commented
> Looks like the file references/release_notes.adoc is missing

Classic case of "How do I git?" :man_facepalming:

2021-08-16 15:27 UTC, simu approved these changes
LGTM overall

2021-08-16 15:27 UTC, simu commented on docs/modules/ROOT/pages/references/release_notes.adoc
> +OpenShift 4.8 was release at 2021-08-02.
```suggestion
OpenShift 4.8 was released on 2021-08-02.
```

2021-08-17 11:56 UTC, corvus-ch approved these changes

2021-08-17 12:56 UTC, merged