Add documentation on worker groups and volume sizes
appuio/openshift4-docs pull request #119
Opened 2021-09-06 13:21 UTC by glrf

2021-09-06 14:24 UTC, tobru commented
Parts of this PR seem to copy content from https://products.docs.vshn.ch/products/appuio/managed/ocp4_cloudscale.html#_default_configuration_minimum_requirements. How should we avoid having the same information and different places? We could remove it from the product docs and link here, or vice-versa...

2021-09-06 15:16 UTC, simu requested changes
Some typos (might be worth to have a partial for the prelude of the two configuration pages with an attribute to inject `cloudscale.ch` and `Exoscale` as appropriate), and a suggestion to add warnings for configurations which currently aren't supported (although those duplicate more information from the product documentation)

2021-09-06 15:16 UTC, simu commented on docs/modules/ROOT/pages/references/cloudscale/config.adoc
> +
```suggestion

See the https://www.cloudscale.ch/en/pricing[cloudscale.ch pricing doucumentation] for available VM flavors.
```

2021-09-07 07:45 UTC, glrf commented
I actually did not know of the product documentation page. I agree there is some overlap but in the end the two pages serve two different purposes. I'm not sure how useful it actually is to deduplicate this.

As for using partials to unify the two configuration page I'm a little torn. Yes most of it is very similar, but there are differences in naming all over the place. So we would need to use a lot of templating. So the main question is: do we want to maintain two very similar but simple pages, or do we want a single complicated page.

2021-09-07 08:03 UTC, simu requested changes
The remaining suggestions for the Exoscale storage nodes still need to be incorporated.

Re partials: I suggested them because I found the exact same typos in the preamble of both documents.

2021-09-08 12:29 UTC, corvus-ch approved these changes

2021-09-08 14:30 UTC, simu approved these changes

2021-09-10 12:28 UTC, tobru commented
> I actually did not know of the product documentation page. I agree there is some overlap but in the end the two pages serve two different purposes. I'm not sure how useful it actually is to deduplicate this.

Let's keep it as you suggested in this PR, I think that's fine for now.

2021-09-10 12:28 UTC, tobru approved these changes

2021-09-10 13:28 UTC, merged