Document procedure to resize OCP4 worker nodes on cloudscale.ch
appuio/openshift4-docs pull request #178
Opened 2022-05-05 08:51 UTC by TheBigLee

Signed-off-by: Nicolas Bigler <nicolas.bigler@vshn.ch>

2022-05-05 11:50 UTC, simu requested changes
LGTM overall. As always, please keep documentation to one sentence per line and use capitalization.

Please make sure that the new page is added in the navigation (in `docs/modules/ROOT/partials/nav-howtos.adoc`)

2022-05-05 11:50 UTC, simu commented on docs/modules/ROOT/pages/how-tos/cloudscale/increase-worker-node-disk.adoc
> +. In the tenant repo set the parameter `openshift4_terraform.terraform_variables.worker_volume_size_gb` to the desired value.
```suggestion
. In the tenant repo, set the parameter `openshift4_terraform.terraform_variables.worker_volume_size_gb` to the desired value.
```

2022-05-05 11:50 UTC, simu commented on docs/modules/ROOT/pages/how-tos/cloudscale/increase-worker-node-disk.adoc
> +. Run commodore to compile the terraform manifests (should be done automatically via ci pipeline)
```suggestion
. Run Commodore to compile the Terraform manifests (should be done automatically via CI pipeline)
```

2022-05-05 11:50 UTC, simu commented on docs/modules/ROOT/pages/how-tos/cloudscale/increase-worker-node-disk.adoc
> +. Run terraform on the updated terraform manifests (should be done automatically via ci pipeline, the apply stage may be triggered manually)
```suggestion
. Run Terraform on the updated Terraform manifests (should be done automatically via CI pipeline, the apply stage may be triggered manually)
```

2022-05-05 11:50 UTC, simu commented on docs/modules/ROOT/pages/how-tos/cloudscale/increase-worker-node-disk.adoc
> +Once the terraform pipeline ran through, the worker nodes should have the new disk size. However the partition and filesystem on the worker nodes need to be resized manually:
```suggestion
Once the Terraform pipeline ran through, the worker nodes should have the new disk size.
However the partition and filesystem on the worker nodes need to be resized manually:
```

2022-09-01 14:54 UTC, corvus-ch approved these changes

2024-01-12 15:39 UTC, merged