Fix terraform alias to pass ignition url
appuio/openshift4-docs pull request #51
Opened 2020-11-02 15:57 UTC by schemen

Also, add information label regarding version missmatch
between openshift-install and rhcos

2020-11-02 16:07 UTC, srueg approved these changes

2020-11-02 16:26 UTC, corvus-ch requested changes

2020-11-02 16:26 UTC, corvus-ch commented on docs/modules/ROOT/pages/how-tos/cloudscale/install.adoc
> +[NOTE]
```suggestion
[WARNING]
```

Also, move this up to the _Prerequisites_.

2020-11-03 10:59 UTC, corvus-ch approved these changes

2020-11-03 10:59 UTC, corvus-ch commented on docs/modules/ROOT/pages/how-tos/cloudscale/install.adoc
> +
Try to avoid white space changes where ever possible.

2020-11-04 14:49 UTC, merged