Document how to drop alert rules
appuio/openshift4-docs pull request #63
Opened 2021-01-19 14:37 UTC by corvus-ch

2021-01-19 15:26 UTC, tobru requested changes
Besides some typos LGTM. We'll see in practice if this is sufficient or need more explanation.

2021-01-19 15:26 UTC, tobru commented on docs/modules/ROOT/pages/how-tos/monitoring/remove_rules.adoc
> +Somtimes an alert rule doesn't makes sense.
```suggestion
Sometimes an alert rule doesn't make any sense.
```

2021-01-19 15:26 UTC, tobru commented on docs/modules/ROOT/pages/how-tos/monitoring/remove_rules.adoc
> +Be it that the rule is build on assumptions that don't apply.
```suggestion
Be it that the rule is built on assumptions that don't apply.
```

2021-01-19 15:26 UTC, tobru commented on docs/modules/ROOT/pages/how-tos/monitoring/remove_rules.adoc
> +Do so on what ever hierarchy level is the most apropriate.
```suggestion
Do so on whatever hierarchy level is the most appropriate.
```

2021-01-19 16:11 UTC, ccremer approved these changes
I would have found the same typos :)

2021-01-20 09:19 UTC, tobru approved these changes

2021-01-20 16:18 UTC, merged