Investigate and handle alerts
appuio/openshift4-docs pull request #66
Opened 2021-01-22 13:53 UTC by corvus-ch

2021-01-25 15:08 UTC, srueg approved these changes

2021-01-25 15:08 UTC, srueg commented on docs/modules/ROOT/pages/how-tos/monitoring/handle_alerts.adoc
> +Change the configuration within the Sync configuration hierarchy.
```suggestion
Change the configuration within the Syn configuration hierarchy.
```

2021-01-25 15:08 UTC, srueg commented on docs/modules/ROOT/pages/how-tos/monitoring/handle_alerts.adoc
> +Code can behave badly and triggers an alert.
```suggestion
Code can behave badly and trigger an alert.
```

2021-01-25 16:50 UTC, ccremer requested changes

2021-01-25 16:50 UTC, ccremer commented on docs/modules/ROOT/pages/how-tos/monitoring/handle_alerts.adoc
> +== Investigat an alert
```suggestion
== Investigate an alert
```

2021-01-25 16:50 UTC, ccremer commented on docs/modules/ROOT/pages/how-tos/monitoring/handle_alerts.adoc
> +. Lookout for labels and annotations
```suggestion
. Look out for labels and annotations
```

2021-01-25 16:50 UTC, ccremer commented on docs/modules/ROOT/pages/how-tos/monitoring/handle_alerts.adoc
> +Alerts can have a set labels and annotations attached.
```suggestion
Alerts can have a set of labels and annotations attached.
```

2021-01-25 16:50 UTC, ccremer commented on docs/modules/ROOT/pages/how-tos/monitoring/handle_alerts.adoc
> +This is fine as long the issue is expected to resurface again.
I think you meant this?
```suggestion
This is fine as long the issue is not expected to resurface again.
```

2021-01-25 16:50 UTC, ccremer commented on docs/modules/ROOT/pages/how-tos/monitoring/handle_alerts.adoc
> +A likely case for this would be a commodore component not allowing to configure certain aspects.
```suggestion
A likely case for this would be a Commodore component not allowing to configure certain aspects. 
```

2021-01-25 16:50 UTC, ccremer commented on docs/modules/ROOT/pages/how-tos/monitoring/handle_alerts.adoc
> +This would made it too easy.
```suggestion
The decision was to not allow this for now since it would make this too easy.
```

2021-01-26 08:23 UTC, ccremer approved these changes

2021-01-27 15:00 UTC, merged