Update Monitoring design
appuio/openshift4-docs pull request #69
Opened 2021-02-22 09:29 UTC by ccremer

Most of the monitoring documentation was already written.

Added a graphic that helps the reader understanding the design

2021-02-22 09:42 UTC, tobru approved these changes

2021-02-22 12:42 UTC, tobru commented
I just saw the word `SYN` in the graphic, I'd prefer to have `Project Syn` used.

2021-02-22 14:01 UTC, ccremer commented
Done. Thanks!

2021-02-22 14:30 UTC, corvus-ch requested changes
It was a nice catch to pick up the proposel. Ther is one caveat. The user workload monitoring never got tested. So I can not tell if this works or not.

Options to address:
* Drop that part
* Mark it as planned feature
* Have to pages (one explaining effective available features, one containing the ideas/proposal).

2021-02-22 14:30 UTC, corvus-ch commented on docs/modules/ROOT/pages/explanations/cluster_monitoring.adoc
> +To be able to change the existing alerting rules bring our own set of rules based on the https://github.com/openshift/cluster-monitoring-operator[cluster-monitoring-operator] (which in turn is based
```suggestion
To be able to change the existing alerting rules we bring our own set of rules based on the https://github.com/openshift/cluster-monitoring-operator[cluster-monitoring-operator] (which in turn is based on https://github.com/prometheus-operator/kube-prometheus[kube-prometheus]).
```

2021-02-22 14:30 UTC, corvus-ch commented on docs/modules/ROOT/pages/explanations/cluster_monitoring.adoc
> +Additionally we use the https://docs.openshift.com/container-platform/latest/monitoring/monitoring-your-own-services.html[user workload monitoring] feature to add new scrape targets and Prometheus al
Well, that was the idea. If this works or not, I can not tell. At least, we have not testet this yet.

2021-02-22 14:53 UTC, ccremer commented
> Options to address:
> 
>     * Drop that part
> 
>     * Mark it as planned feature
> 
>     * Have to pages (one explaining effective available features, one containing the ideas/proposal).

I'd vote for dropping in that case. Having a ticket/issue in the backlog is not exactly "planned".

2021-03-16 13:12 UTC, corvus-ch approved these changes

2021-03-16 13:13 UTC, merged